name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "AWESOME that you contribute to our Repo, thanks a lot!"
        pr-message: "EXCITING to see your first Pull-Request, thanks for contribution!"
